Implemented Service and mission page
DominikNITA/ProjetGL2122 pull request #13
Opened 2022-01-25 00:49 UTC by bubsi-91

Server side:
-Fixed some issues with routing and json objects

Client side:
-Added Service page:
  -Missions and Users lists
  -Now visible for any users
  -Buttons only for Leader Role
  -Create and update missions

2022-01-25 16:59 UTC, DominikNITA requested changes

2022-01-25 16:59 UTC, DominikNITA commented on server/src/services/missionService.ts
> +    return mission.startDate <= mission.endDate ? true : false;
tu peux mettre juste : return mission.startDate <= mission.endDate;
le true false est inutil

2022-01-25 16:59 UTC, DominikNITA commented on client/src/pages/ServicePage.tsx
> +    }, [missions, auth, selectedMission.reloadHack]);
Il y a un petit problème ici: useEffect est appelée quand au moins une des variables dans sa liste de dépendances change ([missions, auth, selectedMission.reloadHack] dans ce cas). Cependant, à l'intérieur de cette fonction on modifie les missions donc, la fonction se relance et nous avons une boucle infinie. Est-ce qu'on peut supprimer les missions de cette liste ou c'est nécessaire de l'avoir ici?
![image](https://user-images.githubusercontent.com/36695471/151021893-dfbea8df-df17-4fa4-b550-8e2b7a5b0970.png) - +3k requetes en quelques secondes

2022-01-25 16:59 UTC, DominikNITA commented on client/src/clients/serviceClient.ts
> +        .post(`/service/${serviceId}/mission`, { mission })
Comment ca marche? Je vois que dans le serviceRouter on recois la mission avec req.body.mission. Axios le met automatiquement dans une variable avec le meme nom?

2022-01-25 17:04 UTC, bubsi-91 commented on client/src/clients/serviceClient.ts
> +        .post(`/service/${serviceId}/mission`, { mission })
Oui apparement ça marche comme ça. De base je voulais juste voir si il était possible d'envoyer le body en "brut" (sans passer par un objet mission quoi). Mais du coup il faut quand même passer par req.body.mission

2022-01-26 17:05 UTC, bubsi-91 commented on server/src/services/missionService.ts
> +    return mission.startDate <= mission.endDate ? true : false;
fixed

2022-01-26 17:05 UTC, bubsi-91 commented on client/src/pages/ServicePage.tsx
> +    }, [missions, auth, selectedMission.reloadHack]);
Je l'ai supprimé ça marche aussi bien donc fixed

2022-01-26 17:34 UTC, DominikNITA approved these changes
gj

2022-01-26 21:45 UTC, merged